# Configuración para Azure Container Apps (alternativa más avanzada)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-crud-api
  labels:
    app: songs-crud-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: songs-crud-api
  template:
    metadata:
      labels:
        app: songs-crud-api
    spec:
      containers:
      - name: songs-crud-api
        image: songscruda.azurecr.io/songs-crud-api:v1.0
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: songs-crud-service
spec:
  selector:
    app: songs-crud-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
